//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int custId { get; set; }
        public string cust_name { get; set; }
        public string Addres1 { get; set; }
        public string cust_street { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string Post_code { get; set; }
        public string cust_email { get; set; }
        public string cust_tel { get; set; }
        public string cust_business { get; set; }
    }
}
